### ISSUE TITLE
issues with rel=empty

### ISSUE THREAD

**Issue by geemus** [interagent/prmd#169]
I realized today that we are probably using empty a bit innacurately. We use it to mean 202, when really (arguably) it would better describe 204. In fact, I suspect we might really want another value, something like `asynchronous` to better call out this kind of case. Thoughts?

**Comment by ernesto-jimenez** [comment]
nudging @geraintluff about @brandur's comment back in December :)

**Comment by geraintluff** [comment]
What I meant with `{"type":"null"}` is that the client should be prepared to accept a document `null` in response.  I don't think that this should be *exactly* equivalent to expecting `204 No Content`, but I can't imagine a situation where one would be OK and the other not.

My belief is just that clients should be flexible.  If a client is expecting `200 OK` with result `null`, then it should be able to cope with `204 No Content` (and a client expecting `204 No Content` could reasonably throw away any `2XX` response it gets).

So yeah, I don't see an issue here.

**Comment by michaelsauter** [comment]
Sorry if this is a dumb idea - but ... is there a way to override the response status code currently? If not - would it be possible to add this to the schema, and then we could imply an empty response from it?

E.g.
```
links:
  -
    href: "/foo"  
    http_status: 204
```

In which case an empty `targetSchema` is implicit.

**Comment by geemus** [comment]
There isn't a direct means within json schema to specify anything about status codes (or headers) for that matter. I think it would be really helpful if this were not the case (and json-schema is extensible). I've had a sense that trying to define ways to specify this stuff more formally would be really valuable, but I keep not-quite managing to get it done. By leaning on a small set of codes as best-practice we are able to mostly avoid the issue, but obviously there end up being some outliers (such as this).

**Comment by waterlink** [comment]
This problem hit me. I was really expecting `rel: empty` result in `204 No content`. But it is not. Taking into account everything that is said before, I can propose the following solution:

```yaml
rel: empty         # 202 Accepted (backwards compatibility, Maybe(deprecated))
rel: no-content    # 204 No content
rel: asynchronous  # 202 Accepted (encouraged to use)
```

I am up for creating a PR for that.

WDYT @geemus ?

**Comment by michaelsauter** [comment]
@waterlink I like the proposal, would be great to have control like this over the status code.

**Comment by geemus** [comment]
Sounds reasonable. That said, I wonder if we should stop burying this inside rel (ie maybe we should just add some attribute that lists the expected status code or codes). What do you think?

**Comment by waterlink** [comment]
```yaml
status:
- 201
- 404
```

Something along these lines?

**Comment by waterlink** [comment]
That is almost the same thing, that @michaelsauter proposed in his comment: https://github.com/interagent/prmd/issues/169#issuecomment-140318789

**Comment by geemus** [comment]
Yeah, probably. My concern just becomes, how do you know which value makes sense to use in examples? Maybe just by convention (the first one) or maybe some other attribute to make it explicit. What do you think?

**Comment by waterlink** [comment]
We can live it as simple as possible and just pick the first one.

Other way would be trying to guess which one is successful, e.g.:

- first find `2xx` and pick first,
- otherwise find `3xx` and pick first,
- otherwise pick first from the whole list.

Other way would be to be explicit about it. If you provide more than one value, then you have to specify which would be used for an example:

```yaml
http_status: 200
# Ok, example will show `200 OK`
```

```yaml
http_status:
- 200
- 201
- 404
# Schema validation will fail, requiring you to provide `default_http_status`
```

```yaml
http_status:
- 200
- 201
- 404
default_http_status: 201
# Ok, example will show `201 Created`
```

Or, make `http_status` more comprehensive object in last case:

```yaml
http_status:
  items:
  - 200
  - 201
  - 404
  default: 201
# Ok, example will show `201 Created`
```

@geemus WDYT? Which would you prefer?
