### ISSUE TITLE
multiple types support

### ISSUE THREAD

**Issue by alex-fedorov** [interagent/prmd#203]
Consider this example:

```yaml
size:
  description: Property size
  example: 45
  types:
    - number
    - string
```

It is valid json schema, but prmd renders only first type. Currently prmd renders only `null` type additionally.
