### ISSUE TITLE
Doesn't work with yaml aliases and refs properly :(

### ISSUE THREAD

**Issue by waterlink** [interagent/prmd#206]
Example:

```yaml
definitions:
  example: &an_example
    type: object
    properties:
      id:
        "$ref": "#/attributes/id"
      name:
        "$ref": "#/attributes/name"
  example_list:
    type: array
    items: *an_example
```

Fails on verify step, because `prmd` inserts `/definitions` in all refs, but in case of yaml aliases, they will be the same object in memory, and `prmd` will mutate same strings twice, effectively making aliases look like:

```json
{
  "$ref": "#/definitions/definitions/definitions/attributes/name"
}
```

Which is sad.

It is probably pretty easy to fix, so I will try to take a stab on it, when I have some time.
