### ISSUE TITLE
schema property validation doesn't resolve references

### ISSUE THREAD

**Issue by reesew** [interagent/prmd#238]
This may be a misunderstanding on my part on the limitations of schemas and validations, but it seems like the `$ref` feature should allow a copy-paste type replacement for reuse. I'm unable to complete the `verify` step until I add the fields the `schema` link property expects, even though the replacement provided by `$ref` has those fields.

What I expect to work:
`widget.yaml`
```yaml
---
$schema: http://json-schema.org/draft-04/hyper-schema
title: API - Widget
description: widgets
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of widget
    readOnly: true
    format: uuid
    type:
    - string
  identity:
    anyOf:
    - $ref: /schemata/widget#/definitions/id
links:
- description: Update an existing widget.
  href: /widgets/{(%2Fschemata%2Fwidget%23%2Fdefinitions%2Fidentity)}
  method: PUT
  rel: update
  schema:
    $ref: "/schemata/widget"
  targetSchema:
    $ref: "/schemata/widget"
  title: Update
properties:
  id:
    $ref: /schemata/widget#/definitions/id
id: schemata/widget
```
But that fails validation because the `schema` field doesn't have `type` and `property` fields, even though `$ref: "/schemata/widget"` resolves to an object with those fields. For some reason, I need to update the `schema` field to include those properties, like so
`widget.yaml`
```yaml
---
$schema: http://json-schema.org/draft-04/hyper-schema
title: API - Widget
description: widgets
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of widget
    readOnly: true
    format: uuid
    type:
    - string
  identity:
    anyOf:
    - $ref: /schemata/widget#/definitions/id
links:
- description: Update an existing widget.
  href: /widgets/{(%2Fschemata%2Fwidget%23%2Fdefinitions%2Fidentity)}
  method: PUT
  rel: update
  schema:
    type: object
    properties: {
        id:
          $ref: /schemata/widget#/definitions/id
    }
  targetSchema:
    $ref: "/schemata/widget"
  title: Update
properties:
  id:
    $ref: /schemata/widget#/definitions/id
id: schemata/widget
```
