### ISSUE TITLE
Attributes table empty in 0.8.0

### ISSUE THREAD

**Issue by mathroc** [interagent/prmd#240]
When generating documentation with prmd 0.8.0 the Attributes tables are empty (there only is the "Name 	Type 	Description 	Example" header)

it's working correctly with 0.7.4

I tried to find the commit which bring this regression, I found that it's working at 7b62d00d90d8ccc93ba1383c1e13e0eca03866c6 and it's not anymore at 5b2f0e9cf6cf92af3aa7cefcb8acd019b13637e3 so I guess it's one of those commits : https://github.com/interagent/prmd/compare/7b62d00d90d8ccc93ba1383c1e13e0eca03866c6...5b2f0e9cf6cf92af3aa7cefcb8acd019b13637e3

**Comment by geemus** [comment]
Thats no good. Could you share the schema you are having trouble with so I can ensure things get fixed as expected? Thanks!

**Comment by mathroc** [comment]
here two files that can be used to reproduce the problem : 

```yaml
# schemata/calendars.yaml
$schema: 'http://json-schema.org/draft-04/hyper-schema'
title: Calendars
links:
  -
    description: 'Collection of calendars for a user'
    href: '/users/nnn/calendars'
    method: GET
    rel: self
    title: Query
properties:
  calendars:
    type: array
    items:
      $ref: '/schemata/model-calendar#'
required:
  - calendars
type:
  - object
id: schemata/calendars
```


```yaml
# schemata/model-calendar.yaml
$schema: 'http://json-schema.org/draft-04/hyper-schema'
title: Calendar
definitions:
  identity:
    description: 'unique identity of calendar'
    example: ad62e9ea-84df-4c8e-99b8-55a9ae3b746b
    type:
      - string
  created_at:
    description: 'creation date of calendar'
    example: '2015-01-01 15:01:01'
    type:
      - string
  updated_at:
    description: 'updated date of current version of calendar'
    example: '2015-01-01 15:01:01'
    type:
      - string
  author_identity:
    description: 'author of calendar'
    example: '1'
    type:
      - string
  name:
    description: 'name of calendar'
    type:
      - string
properties:
  id:
    $ref: '/schemata/model-calendar#/definitions/identity'
  created_at:
    $ref: '/schemata/model-calendar#/definitions/created_at'
  updated_at:
    $ref: '/schemata/model-calendar#/definitions/updated_at'
  name:
    $ref: '/schemata/model-calendar#/definitions/name'
type:
  - object
required:
  - id
  - created_at
  - updated_at
  - name
id: schemata/model-calendar
```

I just realized this schema is not correct (prmd verify complains about it) but it used to produce what I expected and now it does not anymore: The "Calendars" Attributes table is empty. the strange thing is that the Calendars response example is OK

**Comment by mathroc** [comment]
I managed to fix the schema (verify does not complain anymore) and I still have the problem only on 0.8.0 :

```yaml
# schemata/calendars.yaml
$schema: 'http://json-schema.org/draft-04/hyper-schema'
title: Calendars
type: object
description: About calendars
definitions:
  identity:
    anyOf:
      - "$ref": "/schemata/calendars#/definitions/id"
  id:
    description: 'unique id of calendar'
    example: ad62e9ea-84df-4c8e-99b8-55a9ae3b746b
    format: uuid
    type: string
  name:
    description: 'name of calendar'
    type: string
  calendar:
    description: A calendar
    type: object
    properties:
      id:
        $ref: '/schemata/calendars#/definitions/id'
      name:
        $ref: '/schemata/calendars#/definitions/name'
    required:
      - id
      - name
links:
  - description: 'A calendar response'
    href: '/a-calendar'
    method: GET
    rel: self
    title: Query
properties:
  calendars:
    description: foobar
    type: array
    items:
      $ref: '/schemata/calendars#/definitions/calendar'
required:
  - calendars
id: schemata/calendars
```
