### ISSUE TITLE
Missing "description" in subschema raises "No subschema in "anyOf" matched."

### ISSUE THREAD

**Issue by ryanbrainard** [interagent/prmd#329]
I had a property that looked like this:

```yaml
  channel:
    type:
    - object
    properties:
      id:
        "$ref": "/schemata/channel#/definitions/id"
      name:
        "$ref": "/schemata/channel#/definitions/name"
```

which was raising the error:

    schema/schema.json: #/definitions/approval/properties/channel: failed schema #/definitions/resource/properties/properties/patternProperties/^[a-z0-9][a-zA-Z0-9_]*[a-zA-Z0-9]$: No subschema in "anyOf" matched.

This error was not very helpful at explaining what the problem actually was. After much trial and error, it was the fact that the `description` was missing. i.e. this fixed it:

```yaml
  channel:
    description: THIS IS THE FIX
    type:
    - object
    properties:
      id:
        "$ref": "/schemata/channel#/definitions/id"
      name:
        "$ref": "/schemata/channel#/definitions/name"
```

Can we please have a better error message for this?

*prmd 0.13.0*
